language: node_js
node_js:
  - 13

services:
  - docker

branches:
  only:
    - main

install:
  - npm install -g serverless

script:
  # Build the binary file
  - make build
  # deploy to AWS lambda
  - sls deploy

environments:
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}