matrix:
  include:
    - language: go
      go:
        - 1.16.x
      script:
        - go mod download
        - make build

    - language: node.js
      node_js: "12.0"
      before_script:
        - npm install -g serverless
      environments:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      script:
        - sls deploy