service: exchangeio
#app: exchangeio need to be loggein serverless.io
#org: matthausen

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-west-2

functions:
  exchange:
    handler: bin/exchange
    events:
      - schedule: rate(24 hours)
      - httpApi:
          path: /exchange
          method: get

# Lambda function's IAM Role statements here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# environment variables here
#  environment:
#    variable1: value1